version: '3.9'


services:
  airport_service:
    restart: on-failure
    container_name: airport_service
    build: ./airport_service/
    ports:
      - "8000:80"

  status_service:
    restart: on-failure
    container_name: status_service
    build: status_service/
    ports:
      - "8001:80"

